### ISSUE TITLE
CredentialsWithQuotaProject

### ISSUE THREAD

**Issue by Downchuck** [mvanholsteijn/python-gcloud-config-helper#1]
Seems this is not quite picking up the strange CredentialsWithQuotaProject / _quota_project_id quite how the speech api would like.

https://github.com/googleapis/google-auth-library-python/blob/master/google/auth/credentials.py#L52

https://github.com/googleapis/google-auth-library-python/blob/master/google/oauth2/credentials.py#L57

```
credentials, projectId = gcloud_config_helper.default()
credentials._quota_project_id = projectId
```

**Comment by mvanholsteijn** [comment]
That is strange. In gcloud i cannot configure a quota project at all, except for the default application credentials, can i?

**Comment by mvanholsteijn** [comment]
Ok. I have release version 0.3.0 of the library. Please use the following construct to create the credentials for the speech API:

```python
credentials, project = gcloud_config_helper.default()
credentials = credentials.with_quota_project(project)

client = speech.SpeechClient(credentials=credentials)
```

or use:
```python
credentials, project = gcloud_config_helper.default()
client = speech.SpeechClient(credentials=credentials, client_options=ClientOptions(quota_project_id=project))
```

Let me know if this works for you.

**Comment by Downchuck** [comment]
Confirmed, both work!
